PT_BR = {
-- #ChatBox
"#006fff( #FFFFFFEvento #006fff) ",
"#006fffSuas armas foram removidas! ",
"#006fffTodos ganharam armas do evento!",
"Já existe um evento em andamento.",
" Criou um novo evento. Use #ff0000/eir #ffffffpara participar!",
"Não existe um evento em andamento.",
"Eventos removidos por ",
" Foi para o evento.",
"Você ganhou a arma do evento!",
"#FF0000O evento está trancado.",
"#FF0000Você selecionou uma arma invalida!!",
" Alterou sua vida para para ",
" Alterou seu colete para ",
" Destrancou o evento.",
" Trancou o evento.",
" Congelou todos.",
" Descongelou todos.",
"Veiculo Invalido",
" Deu um veiculo para todos.",
" Removeu todos os veiculos.",
" Reparou todos os veiculos.",
"Eventos removidos.",
-- #GUI
"Eventos",
"Opções",
"Dar Arma",
"Dar Veiculo",
"Definir Vida",
"Definir Colete",
"Congelar Todos",
"Reparar Veiculos",
"Destruir Veiculos",
"Trancar Evento",
"Novo Evento",
"Criar Evento",
"Dimensão:",
"Interior:",
"Entrar no Evento",
"Destruir Evento",
"Fechar",
}

LANGUAGE = PT_BR